export const theme = {
  colors: {
    text: '#fff',
    silver: '#C0C0C0',
    textSecondary: '#B0B0B0',
    textMuted: '#888',
    primary: '#FFD700',
    errorLight: '#FF6B6B',
    error: '#FF2222',
    success: '#4CAF50',
    bronze: '#CD7F32',
    disabled: '#555',
    border: '#333',
    surface: '#23242A',
    background: '#181A20',
    modalBackground: 'rgba(0, 0, 0, 0.5)',
    shadow: '#000',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 15,
    xl: 20,
    xxl: 24,
    xxxl: 30,
    huge: 40,
    massive: 50,
  },
  borderRadius: {
    xs: 8,
    sm: 10,
    md: 12,
    lg: 15,
    xl: 18,
    xxl: 20,
    round: 25,
    circle: 60,
  },
  fonts: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    xxl: 22,
    xxxl: 28,
    title: 32,
  },
  shadows: {
    small: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 4,
    },
    button: {
      shadowColor: '#FFD700',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 6,
      elevation: 2,
    },
    profileButton: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 2,
      elevation: 3,
    },
  },
};