
export const defaultProfileImages = [
  'bear.jpeg',
  'big_bird.jpeg',
  'bird.jpeg',
  'chipmunk.jpeg',
  'deer.jpeg',
  'dog.jpeg',
  'duck.jpeg',
  'eagle.jpeg',
  'hiena.jpeg',
  'monkey.jpeg',
  'moskus.jpeg',
  'mouse.jpeg',
  'pigeon.jpeg',
  'seal.jpeg',
  'small_bird.jpeg',
  'whale.jpeg',
  'wolf.jpeg',
];

export const defaultProfileImageMap: { [key: string]: any } = {
  'bear.jpeg': require('../../assets/images/default/bear.jpeg'),
  'big_bird.jpeg': require('../../assets/images/default/big_bird.jpeg'),
  'bird.jpeg': require('../../assets/images/default/bird.jpeg'),
  'chipmunk.jpeg': require('../../assets/images/default/chipmunk.jpeg'),
  'deer.jpeg': require('../../assets/images/default/deer.jpeg'),
  'dog.jpeg': require('../../assets/images/default/dog.jpeg'),
  'duck.jpeg': require('../../assets/images/default/duck.jpeg'),
  'eagle.jpeg': require('../../assets/images/default/eagle.jpeg'),
  'hiena.jpeg': require('../../assets/images/default/hiena.jpeg'),
  'monkey.jpeg': require('../../assets/images/default/monkey.jpeg'),
  'moskus.jpeg': require('../../assets/images/default/moskus.jpeg'),
  'mouse.jpeg': require('../../assets/images/default/mouse.jpeg'),
  'pigeon.jpeg': require('../../assets/images/default/pigeon.jpeg'),
  'seal.jpeg': require('../../assets/images/default/seal.jpeg'),
  'small_bird.jpeg': require('../../assets/images/default/small_bird.jpeg'),
  'whale.jpeg': require('../../assets/images/default/whale.jpeg'),
  'wolf.jpeg': require('../../assets/images/default/wolf.jpeg'),
};
