import { Platform, StyleSheet } from 'react-native';
import { globalStyles } from '../globalStyles';

export const loginStyles: any = StyleSheet.create({
  darkContainer: {
    backgroundColor: '#0F131A',
  },
  screenContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'web' ? 34 : 20,
    paddingBottom: 22,
    overflow: 'hidden',
  },
  screenContentRegister: {
    justifyContent: 'flex-start',
    paddingTop: Platform.OS === 'web' ? 24 : 14,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#0F131A',
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  brandSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  brandLogo: {
    width: 72,
    height: 72,
    marginBottom: 4,
    opacity: 0.95,
  },
  appName: {
    ...globalStyles.titleText,
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '800',
    color: '#E0B84F',
    textShadowColor: 'rgba(0, 0, 0, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
    letterSpacing: -0.3,
  },
  welcomeText: {
    fontSize: 17,
    color: '#E5E7EB',
    textAlign: 'center',
    marginTop: 4,
    fontWeight: '500',
  },
  cardWrapper: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    position: 'relative',
    paddingVertical: 0,
    overflow: 'visible',
  },
  cardBorderFade: {
    position: 'absolute',
    top: 1,
    bottom: 1,
    left: 1,
    right: 1,
    borderRadius: 24,
    backgroundColor: 'rgba(241, 210, 120, 0.03)',
    shadowColor: '#F1D278',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: Platform.OS === 'web' ? 0.44 : 0.31,
    shadowRadius: Platform.OS === 'web' ? 44 : 30,
    elevation: 5,
    zIndex: 3,
  },
  authCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#D4AF37',
    borderRadius: 24,
    backgroundColor: '#222834',
    overflow: 'hidden',
    marginHorizontal: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 2,
  },
  cardHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 64,
    zIndex: 3,
  },
  authCardGradient: {
    padding: Platform.OS === 'web' ? 28 : 24,
  },
  modeSwitchContainer: {
    flexDirection: 'row',
    backgroundColor: 'rgba(9, 12, 19, 0.74)',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.08)',
    padding: 4,
    marginBottom: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  modeSwitchIndicator: {
    position: 'absolute',
    top: 4,
    bottom: 4,
    left: 4,
    borderRadius: 10,
    backgroundColor: 'rgba(212, 175, 55, 0.24)',
    borderWidth: 1,
    borderColor: 'rgba(236, 211, 122, 0.72)',
  },
  modeButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    zIndex: 2,
  },
  modeButtonActive: {
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  modeButtonText: {
    color: '#A8B1C1',
    fontSize: 14,
    fontWeight: '600',
  },
  modeButtonTextActive: {
    color: '#F4DC8C',
  },
  fieldLabel: {
    ...globalStyles.label,
    color: '#FFFFFF',
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '500',
  },
  formInputGroup: {
    marginBottom: 28,
  },
  inputShell: {
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#0F121A',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  },
  inputShellWithIcon: {
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#0F121A',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputShellFocused: {
    borderColor: 'rgba(241, 210, 120, 0.8)',
    shadowColor: '#F1D278',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: Platform.OS === 'web' ? 0.26 : 0.18,
    shadowRadius: Platform.OS === 'web' ? 10 : 7,
    elevation: 3,
  },
  authInput: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: '#CCD4DF',
    fontSize: 16,
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  authInputWithIcon: {
    flex: 1,
    paddingRight: 8,
  },
  eyeButton: {
    width: 48,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  ctaButton: {
    borderRadius: 999,
    marginTop: 6,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0, 0, 0, 0.08)',
    minHeight: 52,
    justifyContent: 'center',
    shadowColor: '#ECD37A',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: Platform.OS === 'web' ? 0.35 : 0.24,
    shadowRadius: 16,
    elevation: 6,
  },
  ctaGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaLoader: {
    marginRight: 8,
  },
  ctaButtonText: {
    color: '#080808',
    fontSize: 21,
    fontWeight: '700',
    letterSpacing: 0,
  },
  ctaShineSweep: {
    position: 'absolute',
    top: -18,
    width: 90,
    height: 110,
    backgroundColor: 'rgba(255, 255, 255, 0.55)',
    opacity: 0.7,
  },
});
