import { Platform, StyleSheet } from 'react-native';
import { globalStyles } from '../globalStyles';
import { theme } from '../theme';

export const loginScreenTokens = {
  placeholderTextColor: theme.colors.textSecondary,
  iconTint: theme.colors.textSecondary,
  loaderColor: theme.colors.shadowDim,
  backgroundGradientColors: [theme.gradients.loginBackgroundStart, theme.gradients.loginBackgroundEnd] as const,
  cardHighlightGradientColors: [theme.effects.white08, theme.effects.white00] as const,
  authCardGradientColors: [theme.effects.authGradientFrom, theme.effects.authGradientTo] as const,
  ctaGradientColors: [theme.gradients.ctaStart, theme.gradients.ctaEnd] as const,
};

export const loginStyles: any = StyleSheet.create({
  pageContainer: {
    padding: 0,
  },
  darkContainer: {
    backgroundColor: theme.colors.backgroundDeep,
  },
  screenContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingTop: Platform.OS === 'web' ? 34 : 20,
    paddingBottom: 22,
    overflow: 'hidden',
  },
  screenContentRegister: {
    justifyContent: 'flex-start',
    paddingTop: Platform.OS === 'web' ? 24 : 14,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: theme.colors.backgroundDeep,
  },
  backgroundGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  brandSection: {
    alignItems: 'center',
    marginBottom: 20,
  },
  brandLogo: {
    width: 72,
    height: 72,
    marginBottom: 4,
    opacity: 0.95,
  },
  appName: {
    ...globalStyles.titleText,
    fontSize: 42,
    lineHeight: 46,
    fontWeight: '800',
    color: theme.colors.primarySoft,
    textShadowColor: theme.effects.black50,
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
    letterSpacing: -0.3,
  },
  welcomeText: {
    fontSize: 17,
    color: theme.colors.textStrong,
    textAlign: 'center',
    marginTop: 4,
    fontWeight: '500',
  },
  cardWrapper: {
    width: '100%',
    maxWidth: 400,
    alignSelf: 'center',
    position: 'relative',
    paddingVertical: 0,
    overflow: 'visible',
  },
  cardBorderFade: {
    position: 'absolute',
    top: 1,
    bottom: 1,
    left: 1,
    right: 1,
    borderRadius: 24,
    backgroundColor: theme.effects.gold03,
    shadowColor: theme.colors.primaryGlow,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: Platform.OS === 'web' ? 0.44 : 0.31,
    shadowRadius: Platform.OS === 'web' ? 44 : 30,
    elevation: 5,
    zIndex: 3,
  },
  authCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: theme.gradients.ctaStart,
    borderRadius: 24,
    backgroundColor: theme.colors.backgroundCard,
    overflow: 'hidden',
    marginHorizontal: 0,
    shadowColor: theme.colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
    zIndex: 2,
  },
  cardHighlight: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 64,
    zIndex: 3,
  },
  authCardGradient: {
    padding: Platform.OS === 'web' ? 28 : 24,
  },
  modeSwitchContainer: {
    flexDirection: 'row',
    backgroundColor: theme.effects.modeTrack,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: theme.effects.white08,
    padding: 4,
    marginBottom: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  modeSwitchIndicator: {
    position: 'absolute',
    top: 4,
    bottom: 4,
    left: 4,
    borderRadius: 10,
    backgroundColor: theme.effects.modeIndicatorBg,
    borderWidth: 1,
    borderColor: theme.effects.modeIndicatorBorder,
  },
  modeButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    borderRadius: 10,
    zIndex: 2,
  },
  modeButtonActive: {
    backgroundColor: 'transparent',
    borderWidth: 0,
  },
  modeButtonText: {
    color: theme.colors.textModeIdle,
    fontSize: 14,
    fontWeight: '600',
  },
  modeButtonTextActive: {
    color: theme.colors.textModeActive,
  },
  fieldLabel: {
    ...globalStyles.label,
    color: theme.colors.white,
    marginBottom: 8,
    fontSize: 14,
    fontWeight: '500',
  },
  formInputGroup: {
    marginBottom: 28,
  },
  inputShellWithIcon: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  authInput: {
    borderWidth: 0,
    backgroundColor: 'transparent',
    color: theme.colors.textInput,
    fontSize: 16,
    paddingVertical: 13,
    paddingHorizontal: 14,
  },
  authInputWithIcon: {
    flex: 1,
    paddingRight: 8,
  },
  eyeButton: {
    width: 48,
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  ctaButton: {
    borderRadius: 999,
    marginTop: 6,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: theme.effects.black08,
    minHeight: 52,
    justifyContent: 'center',
    shadowColor: theme.colors.primaryGlowStrong,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: Platform.OS === 'web' ? 0.35 : 0.24,
    shadowRadius: 16,
    elevation: 6,
  },
  ctaGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaContentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ctaLoader: {
    marginRight: 8,
  },
  ctaButtonText: {
    color: theme.colors.textOnGold,
    fontSize: 21,
    fontWeight: '700',
    letterSpacing: 0,
  },
  ctaShineSweep: {
    position: 'absolute',
    top: -18,
    width: 90,
    height: 110,
    backgroundColor: theme.effects.white55,
    opacity: 0.7,
  },
});
